import { dashbaordNavHeight, dashboardLayoutPad, dashboardDrawerWidth } from '../../constants/dimensions';

export const styles = {
  nav: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    pl: { xs: `${dashboardLayoutPad}px`, md: `${dashboardLayoutPad}px` },
    pr: `${dashboardLayoutPad}px`,
    height: `${dashbaordNavHeight}px`,
    backgroundColor: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 100,
    width: '100%',
    boxShadow: '0 8px 8px rgba(0, 0, 0, 0.1)',
  },
  navLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  navTitle: {
    fontFamily: 'Mada, sans-serif',
    fontWeight: 600,
    fontSize: { xs: '20px', md: '28px' },
    letterSpacing: '2px',
    color: '#0C0B18',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  contanier: {
    position: 'absolute',
    left: '300px',
    right: 0,
    display: 'flex',
    justifyContent: 'center',
  },
  navRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    maxWidth: '100%',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },

  searchBox: {
    display: { xs: 'none', md: 'flex' },
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: '32px',
    border: '1px solid #E2E2E2',
    height: '40px',
    width: '270px',
    padding: '0 12px',
    gap: '8px',

  },
  searchIcon: {
    width: '18px',
    height: '18px',
    color: '#646464',
  },
  searchInput: {
    fontFamily: 'Mada, sans-serif',
    fontSize: '14px',
    color: '#646464',
  },
  notificationIcon: {
    display: { xs: 'none', md: 'flex' },
    alignItems: 'center',
    justifyContent: 'center',
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    border: '1px solid #D9D9D9',
    cursor: 'Pointer'
  },
  iconSize: {
    width: '18px',
    height: '18px',
    color: '#6D6C6B',
  },

  navRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
  },
  searchBox: {
    display: { xs: 'none', md: 'flex' },
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: '32px',
    border: '1px solid #E2E2E2',
    height: '40px',
    width: '270px',
    padding: '0 12px',
    gap: '8px',
  },
  searchIcon: {
    width: '18px',
    height: '18px',
    color: '#646464',
  },
  searchInput: {
    fontFamily: 'Mada, sans-serif',
    fontSize: '14px',
    color: '#646464',
  },
  notificationDropdown: {
    position: 'absolute',
    top: '50px',
    right: 0,
    backgroundColor: '#fff',
    border: '1px solid #e0e0e0',
    borderRadius: '8px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
    padding: '8px 0',
    zIndex: 999,
    minWidth: '200px',
    maxWidth: '250px',
  },
  
  notificationIcon: {
    display: { xs: 'none', md: 'flex' },
    alignItems: 'center',
    justifyContent: 'center',
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    border: '1px solid #D9D9D9',
    cursor: 'Pointer'
  },
  iconSize: {
    width: '18px',
    height: '18px',
    color: '#6D6C6B',
  },
  userInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    cursor: 'pointer',
  },
  userAvatar: {
    width: '50px',
    height: '50px',
    borderRadius: '60%',
    backgroundColor: '#FFFFFF',
    border: '1px solid #000',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  userDetails: {
    display: { xs: 'none', md: 'flex' },
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  userName: {
    fontFamily: 'Mada, sans-serif',
    fontWeight: 600,
    fontSize: '15px',
    color: '#0C0B18',
    whiteSpace: 'nowrap',
  },
  userHandle: {
    fontFamily: 'Mada, sans-serif',
    fontWeight: 400,
    fontSize: '10px',
    color: '#646464',
    whiteSpace: 'nowrap',
  },
  arrowIcon: {
    display: { xs: 'none', md: 'block' },
    width: '22px',
    height: '22px',
    color: '#646464',
    cursor: 'pointer',
  },
  dropdownMenu: {
    position: 'absolute',
    top: '60px',
    right: 0,
    backgroundColor: '#fff',
    border: '1px solid #e0e0e0',
    borderRadius: '8px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
    padding: '8px 0',
    zIndex: 999,
    minWidth: '160px',
  },
  dropdownItem: {
    padding: '8px 16px',
    fontSize: '14px',
    fontFamily: 'Mada, sans-serif',
    color: '#333',
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: '#f5f5f5',
    },
  },

};

