export { default as DashboardHome } from "./DashboardHome"
export { default as ManageAdmin } from "./ManageAdmin"
export { default as ManageAdminRoles } from "./ManageAdminRoles"
export { default as ManageCountries} from "./ManageCountries"
export { default as ManageCurrency } from "./ManageCurrency"
export { default as ManageFees } from "./ManageFees"
export { default as ManageRate } from "./ManageRate"
export { default as CryptoCurrencyPage } from "./ManageCurrency/CryptoCurrencyPage"
export { default as FiatCurrencyPage } from "./ManageCurrency/FiatCurrencyPage"
export { default as AllAdminPage } from "./ManageAdmin/AllAdminPage"
export { default as ManageAdminRolesPage } from "./ManageAdmin/ManageAdminRolesPage"
export { default as ManageUser } from "./ManageUser"
export { default as AddRolesPage } from "./AddRolesPage"
export { default as AddFiatPage } from "./AddFiatPage"
export { default as AddCryptoPage } from "./AddCryptoPage"
export { default as User } from "./User"
export { default as ProfilePage } from "./ProfilePage"
export { default as SettingsPage } from "./SettingsPage"
