import { dashboardDrawerWidth, dashboardLayoutPad, dashboardNavHeight } from '../../constants/dimensions';

export const styles = {
  wrap: {
    display: 'flex',
    backgroundColor: '#F5F7FA',
    width: '100%',
    height: '100vh',
    overflowX: 'hidden',
    transition: 'all 0.3s ease',
  },
  togBtn: {
    mr: 2,
    display: { sm: 'none' },
  },
  sidenavWrap: {
    width: (collapsed) => collapsed ? 80 : dashboardDrawerWidth,
    flexShrink: 0,
    display: { xs: 'none', sm: 'block' },
    transition: 'width 0.3s ease-in-out',
  },
  content: {
    flexGrow: 1,
    boxSizing: 'border-box',
    pl: (collapsed) => collapsed ? dashboardLayoutPad : dashboardLayoutPad + (dashboardDrawerWidth - 80),
    pr: `${dashboardLayoutPad}px`,
    pt: `${dashboardNavHeight + dashboardLayoutPad}px`,
    pb: `${dashboardLayoutPad}px`,
    width: '100%',
    minHeight: '100vh',
    height: 'auto',
    backgroundColor: '#F5F7FA',
    transition: 'padding-left 0.3s ease-in-out',
    overflowX: 'hidden',
    overflowY: 'auto',
    minWidth: 0,
    scrollbarWidth: 'none',
    '&::-webkit-scrollbar': {
      display: 'none',
    },
  },
  sidenav: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    background: ' #02042D',
    minHeight: '100vh',
    position: 'relative',
    boxShadow: '0 4px 16px rgba(0, 0, 0, 0.1)',
  },
  collapsedSidenav: {
    width: 80,
    '& .nav-item-text': {
      display: 'none',
    },
    '& .MuiCollapse-root': {
      display: 'none',
    },
    '& .nav-expand-icon': {
      display: 'none',
    },
    '& .nav-icon': {
      display: 'flex !important',
      alignItems: 'center',
      justifyContent: 'center',
      width: 40,
      height: 40,
      minWidth: 40,
      minHeight: 40,
      '& svg': {
        fontSize: '22px !important',
        color: '#B0B3B8 !important',
        display: 'block !important',
        visibility: 'visible !important',
      },
    },
  },
  header: {
    height: '80px',
    display: 'flex',
    alignItems: 'center',
    px: 2,
    justifyContent: 'space-between',
    borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
    background: 'linear-gradient(90deg, #02042D, #1A2A44)',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  toggleButton: {
    color: '#fff',
    borderRadius: '50%',
    width: 48,
    height: 48,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.3s ease',
    background: 'rgba(255, 255, 255, 0.05)',
    '&:hover': {
      background: 'rgba(255, 255, 255, 0.15)',
      transform: 'scale(1.1)',
    },
    '&:active': {
      transform: 'scale(0.95)',
    },
  },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    borderRadius: '12px',
    minHeight: 48,
    transition: 'all 0.3s ease-in-out',
    position: 'relative',
    cursor: 'pointer',
    '&:hover': {
      background: 'rgba(255, 255, 255, 0.1)',
      transform: 'translateX(4px)',
    },
    '&.active': {
      background: 'linear-gradient(90deg, #208BC9, #1A75A8)',
      color: '#fff',
      boxShadow: '0 6px 20px rgba(32, 139, 201, 0.3)',
      '&:hover': {
        background: 'linear-gradient(90deg, #1A75A8, #166799)',
      },
    },
  },
  navItemCollapsed: {
    justifyContent: 'center',
    p: 1,
  },
  navItemExpanded: {
    justifyContent: 'flex-start',
    p: 1.5,
  },
  navIcon: {
    fontSize: 22,
    color: '#B0B3B8',
    transition: 'all 0.3s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    height: 40,
    minWidth: 40,
    minHeight: 40,
    '& svg': {
      color: 'inherit',
    },
  },
  navText: {
    fontSize: '14px',
    fontWeight: 500,
    color: '#B0B3B8',
    transition: 'all 0.3s ease',
  },
  subNavItem: {
    display: 'flex',
    alignItems: 'center',
    borderRadius: '8px',
    minHeight: 40,
    p: 1.5,
    ml: 1,
    transition: 'all 0.3s ease-in-out',
    '&:hover': {
      background: 'rgba(255, 255, 255, 0.1)',
      transform: 'translateX(6px)',
    },
    '&.active': {
      background: 'linear-gradient(90deg, #208BC9, #1A75A8)',
      color: '#fff',
      boxShadow: '0 4px 12px rgba(32, 139, 201, 0.3)',
    },
  },
  tooltip: {
    position: 'absolute',
    left: '100%',
    top: '50%',
    transform: 'translateY(-50%)',
    ml: 1.5,
    px: 1.5,
    py: 0.5,
    background: 'rgba(0, 0, 0, 0.85)',
    color: '#fff',
    borderRadius: 8,
    fontSize: '12px',
    whiteSpace: 'nowrap',
    opacity: 0,
    pointerEvents: 'none',
    transition: 'opacity 0.2s ease-in-out',
    zIndex: 1000,
    boxShadow: '0 4px 16px rgba(0, 0, 0, 0.2)',
    '&::before': {
      content: '""',
      position: 'absolute',
      right: '100%',
      top: '50%',
      transform: 'translateY(-50%)',
      border: '5px solid transparent',
      borderRightColor: 'rgba(0, 0, 0, 0.85)',
    },
  },
  bottomSection: {
    borderTop: '1px solid rgba(255, 255, 255, 0.15)',
    pt: 2,
    mt: 'auto',
  },
  scrollContainer: {
    '&::-webkit-scrollbar': {
      display: 'none',
    },
    scrollbarWidth: 'none',
    scrollbarColor: 'transparent transparent',
  },
};