import { dashboardDrawerWidth, dashboardLayoutPad, dashboardNavHeight } from '../../constants/dimensions';

export const styles = {
  wrap: {
    display: 'flex',
    backgroundColor: 'whitesmoke',
    width: '100%',
    minHeight: '100vh',
    overflowX: 'hidden',
  },
  togBtn: {
    mr: 2,
    display: { sm: 'none' },
  },
  sidenavWrap: {
    width: collapsed => collapsed ? 80 : dashboardDrawerWidth,
    flexShrink: 0,
    display: { xs: 'none', sm: 'block' },
    transition: 'width 0.3s ease',
  },
  content: {
    flexGrow: 1,
    boxSizing: 'border-box',
    pl: collapsed => collapsed ? dashboardLayoutPad : dashboardLayoutPad + (dashboardDrawerWidth - 80),
    pr: `${dashboardLayoutPad}px`,
    pt: `${dashboardNavHeight + dashboardLayoutPad}px`,
    pb: `${dashboardLayoutPad}px`,
    width: '100%',
    minHeight: '100vh',
    backgroundColor: 'whitesmoke',
    transition: 'padding-left 0.3s ease-in-out',
    overflowX: 'hidden',
    minWidth: 0,
  },
  sidenav: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#02042D',
    minHeight: '100vh',
    position: 'relative',
    boxShadow: '2px 0 8px rgba(0, 0, 0, 0.1)',
  },
  collapsedSidenav: {
    width: 80,
    '& .nav-item-text': {
      display: 'none',
    },
    '& .MuiCollapse-root': {
      display: 'none',
    },
    '& .nav-expand-icon': {
      display: 'none',
    },
    '& .nav-icon': {
      display: 'flex !important',
      alignItems: 'center',
      justifyContent: 'center',
      width: 40, // Ensure enough space for icons
      height: 40,
      minWidth: 40,
      minHeight: 40,
      '& svg': {
        fontSize: '22px !important', // Force icon size
        color: 'currentColor !important',
        display: 'block !important',
        visibility: 'visible !important',
      },
    },
  },
  header: {
    height: '80px',
    display: 'flex',
    alignItems: 'center',
    px: 2,
    justifyContent: 'space-between',
    borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
    backgroundColor: '#02042D',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  toggleButton: {
    color: '#fff',
    borderRadius: '50%',
    width: 48,
    height: 48,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.3s ease',
    '&:hover': {
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      transform: 'scale(1.05)',
    },
    '&:active': {
      transform: 'scale(0.95)',
    },
  },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    borderRadius: '12px',
    minHeight: 48,
    transition: 'all 0.3s ease',
    position: 'relative',
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: 'rgba(255, 255, 255, 0.08)',
      transform: 'translateX(2px)',
    },
    '&.active': {
      backgroundColor: '#208BC9',
      boxShadow: '0 4px 12px rgba(32, 139, 201, 0.3)',
      '&:hover': {
        backgroundColor: '#1a75a8',
      },
    },
  },
  navItemCollapsed: {
    justifyContent: 'center',
    p: 1,
  },
  navItemExpanded: {
    justifyContent: 'flex-start',
    p: 1.5,
  },
  navIcon: {
    fontSize: 22,
    color: 'currentColor',
    transition: 'all 0.3s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 40, // Ensure enough space for icons
    height: 40,
    minWidth: 40,
    minHeight: 40,
  },
  navText: {
    fontSize: '14px',
    fontWeight: 500,
    color: 'currentColor',
    transition: 'all 0.3s ease',
  },
  subNavItem: {
    display: 'flex',
    alignItems: 'center',
    borderRadius: '8px',
    minHeight: 40,
    p: 1.5,
    ml: 1,
    transition: 'all 0.3s ease',
    '&:hover': {
      backgroundColor: 'rgba(255, 255, 255, 0.08)',
      transform: 'translateX(4px)',
    },
    '&.active': {
      backgroundColor: '#208BC9',
      boxShadow: '0 2px 8px rgba(32, 139, 201, 0.3)',
    },
  },
  tooltip: {
    position: 'absolute',
    left: '100%',
    top: '50%',
    transform: 'translateY(-50%)',
    ml: 1,
    px: 1.5,
    py: 0.5,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    color: '#fff',
    borderRadius: 1,
    fontSize: '12px',
    whiteSpace: 'nowrap',
    opacity: 0,
    pointerEvents: 'none',
    transition: 'opacity 0.2s ease',
    zIndex: 1000,
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.3)',
    '&::before': {
      content: '""',
      position: 'absolute',
      right: '100%',
      top: '50%',
      transform: 'translateY(-50%)',
      border: '4px solid transparent',
      borderRightColor: 'rgba(0, 0, 0, 0.9)',
    },
  },
  bottomSection: {
    borderTop: '1px solid rgba(255, 255, 255, 0.1)',
    pt: 2,
    mt: 'auto',
  },
  scrollContainer: {
    '&::-webkit-scrollbar': {
      width: 4,
      backgroundColor: 'transparent',
    },
    '&::-webkit-scrollbar-thumb': {
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      borderRadius: 4,
      '&:hover': {
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
      },
    },
    '&::-webkit-scrollbar-track': {
      backgroundColor: 'transparent',
    },
    scrollbarWidth: 'thin',
    scrollbarColor: 'rgba(255, 255, 255, 0.2) transparent',
  },
};