export const styles = {
  sidebar: {
    width: (collapsed) => (collapsed ? 80 : 260),
    flexShrink: 0,
    background: "#02042D",
    minHeight: "100vh",
    boxShadow: "0 4px 16px rgba(0, 0, 0, 0.15)",
    transition: "width 0.3s ease-in-out",
    overflowX: "hidden",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    p: 2,
    borderBottom: "1px solid rgba(0, 255, 204, 0.15)",
    alignItems: "center",
  },
  toggleButton: {
    color: "#fff",
    "&:hover": { background: "rgba(255, 255, 255, 0.1)" },
  },
  navContainer: {
    p: 2,
    display: "flex",
    flexDirection: "column",
    gap: 1,
    mt: 2,
    overflowY: "auto",
    maxHeight: "calc(100vh - 120px)",
    "&::-webkit-scrollbar": { display: "none" },
  },
  navItem: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    height: 48,
    padding: "6px 14px",
    borderRadius: 12,
    color: "#B0B3B8",
    transition: "all 0.25s ease",
    cursor: "pointer",
    "& svg": {
      fontSize: 20,
    },
  },
  navItemActive: {
    background: "linear-gradient(90deg, rgba(0,255,204,0.15), rgba(0,255,204,0.05))",
    color: "#00FFCC",
    boxShadow: "0 0 10px rgba(0,255,204,0.15)",
    "& svg": {
      color: "#00FFCC",
    },
    "&::before": {
      content: '""',
      position: "absolute",
      left: 0,
      top: "10%",
      bottom: "10%",
      width: 3,
      background: "linear-gradient(180deg, #00FFCC 0%, #00BBAA 100%)",
      boxShadow: "0 0 8px rgba(0,255,204,0.7)",
      transition: "all 0.3s ease",
    },
  },
  navText: {
    fontSize: 13,
    fontFamily: "Inter, sans-serif",
    fontWeight: 500,
    color: "inherit",
    whiteSpace: "nowrap",
  },
};
