export const styles = {
    card: {
      width: { xs: "100%", sm: "100%", md: "603px" },
      height: { xs: "auto", sm: 131 },
      borderRadius: "16px",
      p: { xs: 2, sm: 1 },
      mx: "auto",
      marginLeft: { xs: 0, sm: "1px" },
      display: "flex",
      flexDirection: "column",
      justifyContent: "space-between",
      overflow: "hidden",
      marginTop: "4px"
    },
    header: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      flex: 1,
    },
    title: {
      fontWeight: 500,
      fontSize: { xs: 12, sm: 14 },
      lineHeight: { xs: "22px", sm: "26px" },
      letterSpacing: "0.5px",
      color: "#0C0B18",
      mt: 0.7,
    },
    periodSelect: {
      fontWeight: 500,
      fontSize: { xs: 10, sm: 12 },
      lineHeight: { xs: "20px", sm: "24px" },
      letterSpacing: "0.5px",
      color: "#646464",
      mt: 0.7,
      "& .MuiSelect-select": {
        padding: { xs: "2px 12px 2px 8px", sm: "4px 14px 4px 8px" },
        minWidth: { xs: "60px", sm: "80px" },
      },
      "& .MuiOutlinedInput-notchedOutline": {
        border: "none",
      },
    },
    amountContainer: {
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
      flex: 1,
    },
    amount: {
      fontWeight: 800,
      fontSize: { xs: 14, sm: 16 },
      lineHeight: { xs: "30px", sm: "34px" },
      letterSpacing: "0.5px",
      color: "#0C0B18",
      verticalAlign: "middle",
      mt: -0.5,
    },
    percentageBox: {
      width: "50px",
      height: "28px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: "14px",
      marginLeft: "5px",
      mt: -0.5,
    },
    percentage: {
      fontWeight: 400,
      fontSize: { xs: 10, sm: 12 },
      lineHeight: "22px",
      letterSpacing: "0.5px",
      color: "#FFFFFF",
    },
    note: {
      fontWeight: 400,
      fontSize: { xs: 10, sm: 12 },
      lineHeight: "24px",
      letterSpacing: "0.5px",
      color: "#646464",
      marginTop: "5px",
    },
  };