export const styles = {
  card: {
    mt: 3,
    height: { xs: "auto", sm: "546px" },
    borderRadius: "16px",
    p: { xs: 2, sm: 3 },
    backgroundColor: "#fff",
  },
  title: {
    fontFamily: "Mada, sans-serif",
    fontWeight: 600,
    fontSize: { xs: 16, sm: 18 },
    color: "#0C0B18",
    mb: 3,
  },
  cryptoContainer: {
    marginTop: "-5px",
    display: "flex",
    flexDirection: { xs: "column", sm: "row" },
    justifyContent: "space-between",
    flexWrap: "wrap",
    alignItems: "flex-start",
  },
  cryptoColumn: {
    width: { xs: "100%", sm: "48%" },
    mb: { xs: 3, sm: 0 },
  },
  cryptoItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    mb: 2,
    width: "100%",
  },
  cryptoAvatar: {
    width: 30,
    height: 30,
    marginRight: 8,
  },
  cryptoName: {
    fontFamily: "Mada, sans-serif",
    fontWeight: 500,
    fontSize: { xs: 14, sm: 14 },
    color: "#0C0B18",
  },
  cryptoPrice: {
    fontFamily: "Mada, sans-serif",
    fontWeight: 400,
    fontSize: { xs: 12, sm: 12 },
    color: "#646464",
    mt: 0.4,
  },
  cryptoChange: {
    fontFamily: "Mada, sans-serif",
    color: "#377DFF",
    fontSize: { xs: 12, sm: 10 },
    fontWeight: 400,
    lineHeight: "16px",
    ml: 2,
    mt: 2.5,
  },
  cryptoAmount: {
    fontFamily: "Mada, sans-serif",
    color: "#646464",
    fontWeight: 400,
    fontSize: { xs: 14, sm: 12 },
  },
};